<?php

/**
 * Api key for ipstack.com in an array.
 */
return [
    // Output from darksky.net,
    // the whole result for the weather to come.
    "weather_all_to_come" => [
        "latitude" => 42.3601,
        "longitude" => -71.0589,
        "timezone" => "America\/New_York",
        "currently" => [
            "time" => 1664963234,
            "summary" => "Drizzle",
            "icon" => "rain",
            "nearestStormDistance" => 0,
            "precipIntensity" => 0.2,
            "precipIntensityError" => 0.0569,
            "precipProbability" => 0.99,
            "precipType" => "rain",
            "temperature" => 12.42,
            "apparentTemperature" => 12.42,
            "dewPoint" => 11.45,
            "humidity" => 0.94,
            "pressure" => 1014.7,
            "windSpeed" => 4.58,
            "windGust" => 8.82,
            "windBearing" => 17,
            "cloudCover" => 1,
            "uvIndex" => 0,
            "visibility" => 16.093,
            "ozone" => 288.4
        ],
        "minutely" => [
            "summary" => "Possible drizzle stopping in 40 min., starting again 10 min. later.",
            "icon" => "rain",
            "data" => [
                [
                    "time" => 1664963220,
                    "precipIntensity" => 0.205,
                    "precipIntensityError" => 0.0564,
                    "precipProbability" => 0.99,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664963280,
                    "precipIntensity" => 0.1831,
                    "precipIntensityError" => 0.0564,
                    "precipProbability" => 0.98,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664963340,
                    "precipIntensity" => 0.1643,
                    "precipIntensityError" => 0.0541,
                    "precipProbability" => 0.95,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664963400,
                    "precipIntensity" => 0.1496,
                    "precipIntensityError" => 0.0523,
                    "precipProbability" => 0.9,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664963460,
                    "precipIntensity" => 0.1369,
                    "precipIntensityError" => 0.0479,
                    "precipProbability" => 0.87,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664963520,
                    "precipIntensity" => 0.1282,
                    "precipIntensityError" => 0.0444,
                    "precipProbability" => 0.81,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664963580,
                    "precipIntensity" => 0.1211,
                    "precipIntensityError" => 0.0409,
                    "precipProbability" => 0.75,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664963640,
                    "precipIntensity" => 0.116,
                    "precipIntensityError" => 0.0395,
                    "precipProbability" => 0.69,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664963700,
                    "precipIntensity" => 0.1115,
                    "precipIntensityError" => 0.0367,
                    "precipProbability" => 0.64,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664963760,
                    "precipIntensity" => 0.1069,
                    "precipIntensityError" => 0.0351,
                    "precipProbability" => 0.58,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664963820,
                    "precipIntensity" => 0.1038,
                    "precipIntensityError" => 0.0337,
                    "precipProbability" => 0.53,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664963880,
                    "precipIntensity" => 0.1002,
                    "precipIntensityError" => 0.0353,
                    "precipProbability" => 0.48,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664963940,
                    "precipIntensity" => 0.0975,
                    "precipIntensityError" => 0.0359,
                    "precipProbability" => 0.45,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664964000,
                    "precipIntensity" => 0.0985,
                    "precipIntensityError" => 0.0442,
                    "precipProbability" => 0.43,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664964060,
                    "precipIntensity" => 0.1042,
                    "precipIntensityError" => 0.0553,
                    "precipProbability" => 0.4,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664964120,
                    "precipIntensity" => 0.1059,
                    "precipIntensityError" => 0.0599,
                    "precipProbability" => 0.4,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664964180,
                    "precipIntensity" => 0.1186,
                    "precipIntensityError" => 0.0775,
                    "precipProbability" => 0.4,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664964240,
                    "precipIntensity" => 0.1285,
                    "precipIntensityError" => 0.0902,
                    "precipProbability" => 0.41,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664964300,
                    "precipIntensity" => 0.14,
                    "precipIntensityError" => 0.1018,
                    "precipProbability" => 0.4,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664964360,
                    "precipIntensity" => 0.1543,
                    "precipIntensityError" => 0.1111,
                    "precipProbability" => 0.42,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664964420,
                    "precipIntensity" => 0.1637,
                    "precipIntensityError" => 0.1162,
                    "precipProbability" => 0.41,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664964480,
                    "precipIntensity" => 0.1758,
                    "precipIntensityError" => 0.1225,
                    "precipProbability" => 0.41,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664964540,
                    "precipIntensity" => 0.182,
                    "precipIntensityError" => 0.1278,
                    "precipProbability" => 0.44,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664964600,
                    "precipIntensity" => 0.1818,
                    "precipIntensityError" => 0.1284,
                    "precipProbability" => 0.44,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664964660,
                    "precipIntensity" => 0.1852,
                    "precipIntensityError" => 0.1294,
                    "precipProbability" => 0.46,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664964720,
                    "precipIntensity" => 0.1805,
                    "precipIntensityError" => 0.1301,
                    "precipProbability" => 0.47,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664964780,
                    "precipIntensity" => 0.1862,
                    "precipIntensityError" => 0.1343,
                    "precipProbability" => 0.46,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664964840,
                    "precipIntensity" => 0.1769,
                    "precipIntensityError" => 0.1298,
                    "precipProbability" => 0.47,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664964900,
                    "precipIntensity" => 0.1768,
                    "precipIntensityError" => 0.1354,
                    "precipProbability" => 0.48,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664964960,
                    "precipIntensity" => 0.1717,
                    "precipIntensityError" => 0.134,
                    "precipProbability" => 0.48,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664965020,
                    "precipIntensity" => 0.1661,
                    "precipIntensityError" => 0.1391,
                    "precipProbability" => 0.46,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664965080,
                    "precipIntensity" => 0.1583,
                    "precipIntensityError" => 0.131,
                    "precipProbability" => 0.45,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664965140,
                    "precipIntensity" => 0.1569,
                    "precipIntensityError" => 0.1396,
                    "precipProbability" => 0.45,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664965200,
                    "precipIntensity" => 0.1589,
                    "precipIntensityError" => 0.1567,
                    "precipProbability" => 0.43,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664965260,
                    "precipIntensity" => 0.1552,
                    "precipIntensityError" => 0.1662,
                    "precipProbability" => 0.43,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664965320,
                    "precipIntensity" => 0.167,
                    "precipIntensityError" => 0.2115,
                    "precipProbability" => 0.41,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664965380,
                    "precipIntensity" => 0.156,
                    "precipIntensityError" => 0.1676,
                    "precipProbability" => 0.41,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664965440,
                    "precipIntensity" => 0.1653,
                    "precipIntensityError" => 0.2241,
                    "precipProbability" => 0.4,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664965500,
                    "precipIntensity" => 0.1698,
                    "precipIntensityError" => 0.2434,
                    "precipProbability" => 0.39,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664965560,
                    "precipIntensity" => 0.1687,
                    "precipIntensityError" => 0.2395,
                    "precipProbability" => 0.37,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664965620,
                    "precipIntensity" => 0.1802,
                    "precipIntensityError" => 0.2805,
                    "precipProbability" => 0.37,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664965680,
                    "precipIntensity" => 0.1877,
                    "precipIntensityError" => 0.3062,
                    "precipProbability" => 0.36,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664965740,
                    "precipIntensity" => 0.1923,
                    "precipIntensityError" => 0.3426,
                    "precipProbability" => 0.36,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664965800,
                    "precipIntensity" => 0.2074,
                    "precipIntensityError" => 0.3643,
                    "precipProbability" => 0.36,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664965860,
                    "precipIntensity" => 0.1963,
                    "precipIntensityError" => 0.3445,
                    "precipProbability" => 0.35,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664965920,
                    "precipIntensity" => 0.2118,
                    "precipIntensityError" => 0.3848,
                    "precipProbability" => 0.35,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664965980,
                    "precipIntensity" => 0.2136,
                    "precipIntensityError" => 0.3628,
                    "precipProbability" => 0.35,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664966040,
                    "precipIntensity" => 0.2301,
                    "precipIntensityError" => 0.4232,
                    "precipProbability" => 0.37,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664966100,
                    "precipIntensity" => 0.2465,
                    "precipIntensityError" => 0.4405,
                    "precipProbability" => 0.37,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664966160,
                    "precipIntensity" => 0.2347,
                    "precipIntensityError" => 0.4321,
                    "precipProbability" => 0.38,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664966220,
                    "precipIntensity" => 0.252,
                    "precipIntensityError" => 0.453,
                    "precipProbability" => 0.37,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664966280,
                    "precipIntensity" => 0.2438,
                    "precipIntensityError" => 0.442,
                    "precipProbability" => 0.38,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664966340,
                    "precipIntensity" => 0.2491,
                    "precipIntensityError" => 0.4582,
                    "precipProbability" => 0.38,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664966400,
                    "precipIntensity" => 0.263,
                    "precipIntensityError" => 0.4642,
                    "precipProbability" => 0.39,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664966460,
                    "precipIntensity" => 0.2589,
                    "precipIntensityError" => 0.4726,
                    "precipProbability" => 0.39,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664966520,
                    "precipIntensity" => 0.2836,
                    "precipIntensityError" => 0.5367,
                    "precipProbability" => 0.38,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664966580,
                    "precipIntensity" => 0.2772,
                    "precipIntensityError" => 0.4968,
                    "precipProbability" => 0.4,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664966640,
                    "precipIntensity" => 0.288,
                    "precipIntensityError" => 0.5121,
                    "precipProbability" => 0.39,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664966700,
                    "precipIntensity" => 0.2825,
                    "precipIntensityError" => 0.5073,
                    "precipProbability" => 0.39,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664966760,
                    "precipIntensity" => 0.2812,
                    "precipIntensityError" => 0.503,
                    "precipProbability" => 0.38,
                    "precipType" => "rain"
                ],
                [
                    "time" => 1664966820,
                    "precipIntensity" => 0.2757,
                    "precipIntensityError" => 0.5072,
                    "precipProbability" => 0.39,
                    "precipType" => "rain"
                ]
            ]
        ],
        "hourly" => [
            "summary" => "Rain until tonight.",
            "icon" => "rain",
            "data" => [
                [
                    "time" => 1664960400,
                    "summary" => "Possible Light Rain",
                    "icon" => "rain",
                    "precipIntensity" => 0.3464,
                    "precipProbability" => 0.34,
                    "precipType" => "rain",
                    "temperature" => 12.61,
                    "apparentTemperature" => 12.61,
                    "dewPoint" => 11.54,
                    "humidity" => 0.93,
                    "pressure" => 1014.8,
                    "windSpeed" => 4.59,
                    "windGust" => 8.91,
                    "windBearing" => 17,
                    "cloudCover" => 1,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 288
                ],
                [
                    "time" => 1664964000,
                    "summary" => "Light Rain",
                    "icon" => "rain",
                    "precipIntensity" => 0.2445,
                    "precipProbability" => 0.99,
                    "precipType" => "rain",
                    "temperature" => 12.39,
                    "apparentTemperature" => 12.39,
                    "dewPoint" => 11.44,
                    "humidity" => 0.94,
                    "pressure" => 1014.7,
                    "windSpeed" => 4.58,
                    "windGust" => 8.86,
                    "windBearing" => 17,
                    "cloudCover" => 1,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 288.6
                ],
                [
                    "time" => 1664967600,
                    "summary" => "Possible Light Rain",
                    "icon" => "rain",
                    "precipIntensity" => 0.304,
                    "precipProbability" => 0.42,
                    "precipType" => "rain",
                    "temperature" => 12.41,
                    "apparentTemperature" => 12.41,
                    "dewPoint" => 11.47,
                    "humidity" => 0.94,
                    "pressure" => 1014.7,
                    "windSpeed" => 4.78,
                    "windGust" => 9.25,
                    "windBearing" => 16,
                    "cloudCover" => 1,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 289.5
                ],
                [
                    "time" => 1664971200,
                    "summary" => "Possible Light Rain",
                    "icon" => "rain",
                    "precipIntensity" => 0.2944,
                    "precipProbability" => 0.29,
                    "precipType" => "rain",
                    "temperature" => 12.72,
                    "apparentTemperature" => 12.72,
                    "dewPoint" => 11.28,
                    "humidity" => 0.91,
                    "pressure" => 1014.9,
                    "windSpeed" => 5.43,
                    "windGust" => 10.92,
                    "windBearing" => 21,
                    "cloudCover" => 0.97,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 295.2
                ],
                [
                    "time" => 1664974800,
                    "summary" => "Possible Light Rain",
                    "icon" => "rain",
                    "precipIntensity" => 0.374,
                    "precipProbability" => 0.36,
                    "precipType" => "rain",
                    "temperature" => 12.34,
                    "apparentTemperature" => 12.34,
                    "dewPoint" => 11.44,
                    "humidity" => 0.94,
                    "pressure" => 1014.7,
                    "windSpeed" => 5.72,
                    "windGust" => 11.62,
                    "windBearing" => 25,
                    "cloudCover" => 0.95,
                    "uvIndex" => 1,
                    "visibility" => 16.093,
                    "ozone" => 296.4
                ],
                [
                    "time" => 1664978400,
                    "summary" => "Possible Light Rain",
                    "icon" => "rain",
                    "precipIntensity" => 0.3634,
                    "precipProbability" => 0.4,
                    "precipType" => "rain",
                    "temperature" => 11.88,
                    "apparentTemperature" => 11.88,
                    "dewPoint" => 11.67,
                    "humidity" => 0.99,
                    "pressure" => 1014.7,
                    "windSpeed" => 5.58,
                    "windGust" => 11.07,
                    "windBearing" => 27,
                    "cloudCover" => 0.94,
                    "uvIndex" => 2,
                    "visibility" => 16.093,
                    "ozone" => 297
                ],
                [
                    "time" => 1664982000,
                    "summary" => "Possible Light Rain",
                    "icon" => "rain",
                    "precipIntensity" => 0.4454,
                    "precipProbability" => 0.45,
                    "precipType" => "rain",
                    "temperature" => 11.49,
                    "apparentTemperature" => 11.49,
                    "dewPoint" => 11.49,
                    "humidity" => 1,
                    "pressure" => 1014.4,
                    "windSpeed" => 5.6,
                    "windGust" => 10.77,
                    "windBearing" => 28,
                    "cloudCover" => 0.93,
                    "uvIndex" => 3,
                    "visibility" => 16.093,
                    "ozone" => 297.9
                ],
                [
                    "time" => 1664985600,
                    "summary" => "Possible Light Rain",
                    "icon" => "rain",
                    "precipIntensity" => 0.4015,
                    "precipProbability" => 0.44,
                    "precipType" => "rain",
                    "temperature" => 11,
                    "apparentTemperature" => 11,
                    "dewPoint" => 11,
                    "humidity" => 1,
                    "pressure" => 1014.2,
                    "windSpeed" => 5.55,
                    "windGust" => 10.74,
                    "windBearing" => 28,
                    "cloudCover" => 0.93,
                    "uvIndex" => 3,
                    "visibility" => 16.093,
                    "ozone" => 299.1
                ],
                [
                    "time" => 1664989200,
                    "summary" => "Possible Light Rain",
                    "icon" => "rain",
                    "precipIntensity" => 0.511,
                    "precipProbability" => 0.48,
                    "precipType" => "rain",
                    "temperature" => 10.66,
                    "apparentTemperature" => 10.66,
                    "dewPoint" => 10.66,
                    "humidity" => 1,
                    "pressure" => 1014,
                    "windSpeed" => 5.37,
                    "windGust" => 10.53,
                    "windBearing" => 28,
                    "cloudCover" => 0.94,
                    "uvIndex" => 3,
                    "visibility" => 16.093,
                    "ozone" => 299.7
                ],
                [
                    "time" => 1664992800,
                    "summary" => "Possible Light Rain",
                    "icon" => "rain",
                    "precipIntensity" => 0.4368,
                    "precipProbability" => 0.44,
                    "precipType" => "rain",
                    "temperature" => 10.77,
                    "apparentTemperature" => 10.77,
                    "dewPoint" => 10.77,
                    "humidity" => 1,
                    "pressure" => 1013.6,
                    "windSpeed" => 5.24,
                    "windGust" => 10.34,
                    "windBearing" => 27,
                    "cloudCover" => 0.93,
                    "uvIndex" => 3,
                    "visibility" => 16.093,
                    "ozone" => 300.4
                ],
                [
                    "time" => 1664996400,
                    "summary" => "Possible Light Rain",
                    "icon" => "rain",
                    "precipIntensity" => 0.51,
                    "precipProbability" => 0.47,
                    "precipType" => "rain",
                    "temperature" => 11.08,
                    "apparentTemperature" => 11.08,
                    "dewPoint" => 11.08,
                    "humidity" => 1,
                    "pressure" => 1013.3,
                    "windSpeed" => 5.08,
                    "windGust" => 10.07,
                    "windBearing" => 27,
                    "cloudCover" => 0.94,
                    "uvIndex" => 2,
                    "visibility" => 16.093,
                    "ozone" => 301.9
                ],
                [
                    "time" => 1665000000,
                    "summary" => "Rain",
                    "icon" => "rain",
                    "precipIntensity" => 0.9516,
                    "precipProbability" => 0.59,
                    "precipType" => "rain",
                    "temperature" => 12.51,
                    "apparentTemperature" => 12.51,
                    "dewPoint" => 11.78,
                    "humidity" => 0.95,
                    "pressure" => 1013.1,
                    "windSpeed" => 4.71,
                    "windGust" => 9.46,
                    "windBearing" => 25,
                    "cloudCover" => 0.94,
                    "uvIndex" => 1,
                    "visibility" => 16.093,
                    "ozone" => 303.6
                ],
                [
                    "time" => 1665003600,
                    "summary" => "Rain",
                    "icon" => "rain",
                    "precipIntensity" => 1.3683,
                    "precipProbability" => 0.65,
                    "precipType" => "rain",
                    "temperature" => 12.92,
                    "apparentTemperature" => 12.92,
                    "dewPoint" => 11.78,
                    "humidity" => 0.93,
                    "pressure" => 1012.9,
                    "windSpeed" => 4.41,
                    "windGust" => 9.11,
                    "windBearing" => 25,
                    "cloudCover" => 0.96,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 303.2
                ],
                [
                    "time" => 1665007200,
                    "summary" => "Rain",
                    "icon" => "rain",
                    "precipIntensity" => 1.2463,
                    "precipProbability" => 0.64,
                    "precipType" => "rain",
                    "temperature" => 13.44,
                    "apparentTemperature" => 13.44,
                    "dewPoint" => 11.64,
                    "humidity" => 0.89,
                    "pressure" => 1013.1,
                    "windSpeed" => 4.1,
                    "windGust" => 8.54,
                    "windBearing" => 23,
                    "cloudCover" => 0.97,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 302.4
                ],
                [
                    "time" => 1665010800,
                    "summary" => "Possible Light Rain",
                    "icon" => "rain",
                    "precipIntensity" => 0.8806,
                    "precipProbability" => 0.55,
                    "precipType" => "rain",
                    "temperature" => 14.06,
                    "apparentTemperature" => 14.06,
                    "dewPoint" => 11.61,
                    "humidity" => 0.85,
                    "pressure" => 1013.3,
                    "windSpeed" => 3.86,
                    "windGust" => 8.07,
                    "windBearing" => 20,
                    "cloudCover" => 0.98,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 301.9
                ],
                [
                    "time" => 1665014400,
                    "summary" => "Possible Light Rain",
                    "icon" => "rain",
                    "precipIntensity" => 0.657,
                    "precipProbability" => 0.49,
                    "precipType" => "rain",
                    "temperature" => 14.92,
                    "apparentTemperature" => 14.92,
                    "dewPoint" => 11.64,
                    "humidity" => 0.81,
                    "pressure" => 1013.6,
                    "windSpeed" => 3.65,
                    "windGust" => 7.67,
                    "windBearing" => 16,
                    "cloudCover" => 0.99,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 299.9
                ],
                [
                    "time" => 1665018000,
                    "summary" => "Possible Light Rain",
                    "icon" => "rain",
                    "precipIntensity" => 0.5808,
                    "precipProbability" => 0.42,
                    "precipType" => "rain",
                    "temperature" => 15.94,
                    "apparentTemperature" => 15.94,
                    "dewPoint" => 11.83,
                    "humidity" => 0.77,
                    "pressure" => 1013.6,
                    "windSpeed" => 3.43,
                    "windGust" => 7.15,
                    "windBearing" => 10,
                    "cloudCover" => 0.99,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 298.7
                ],
                [
                    "time" => 1665021600,
                    "summary" => "Possible Light Rain",
                    "icon" => "rain",
                    "precipIntensity" => 0.7078,
                    "precipProbability" => 0.39,
                    "precipType" => "rain",
                    "temperature" => 17.05,
                    "apparentTemperature" => 17.05,
                    "dewPoint" => 12.13,
                    "humidity" => 0.73,
                    "pressure" => 1013.4,
                    "windSpeed" => 3.28,
                    "windGust" => 6.79,
                    "windBearing" => 4,
                    "cloudCover" => 0.98,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 297.3
                ],
                [
                    "time" => 1665025200,
                    "summary" => "Possible Light Rain",
                    "icon" => "rain",
                    "precipIntensity" => 0.6868,
                    "precipProbability" => 0.29,
                    "precipType" => "rain",
                    "temperature" => 18.04,
                    "apparentTemperature" => 18.04,
                    "dewPoint" => 12.21,
                    "humidity" => 0.69,
                    "pressure" => 1013.2,
                    "windSpeed" => 3.16,
                    "windGust" => 6.53,
                    "windBearing" => 1,
                    "cloudCover" => 0.97,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 297.6
                ],
                [
                    "time" => 1665028800,
                    "summary" => "Overcast",
                    "icon" => "cloudy",
                    "precipIntensity" => 0.5274,
                    "precipProbability" => 0.23,
                    "precipType" => "rain",
                    "temperature" => 15.06,
                    "apparentTemperature" => 15.06,
                    "dewPoint" => 12.18,
                    "humidity" => 0.83,
                    "pressure" => 1013.1,
                    "windSpeed" => 3.1,
                    "windGust" => 6.56,
                    "windBearing" => 359,
                    "cloudCover" => 0.93,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 297.9
                ],
                [
                    "time" => 1665032400,
                    "summary" => "Mostly Cloudy",
                    "icon" => "partly-cloudy-night",
                    "precipIntensity" => 0.3841,
                    "precipProbability" => 0.18,
                    "precipType" => "rain",
                    "temperature" => 15.11,
                    "apparentTemperature" => 15.11,
                    "dewPoint" => 12.12,
                    "humidity" => 0.82,
                    "pressure" => 1012.9,
                    "windSpeed" => 2.99,
                    "windGust" => 6.43,
                    "windBearing" => 355,
                    "cloudCover" => 0.87,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 297.2
                ],
                [
                    "time" => 1665036000,
                    "summary" => "Overcast",
                    "icon" => "cloudy",
                    "precipIntensity" => 0.3036,
                    "precipProbability" => 0.17,
                    "precipType" => "rain",
                    "temperature" => 15.07,
                    "apparentTemperature" => 15.07,
                    "dewPoint" => 12.1,
                    "humidity" => 0.82,
                    "pressure" => 1013,
                    "windSpeed" => 2.91,
                    "windGust" => 6.65,
                    "windBearing" => 353,
                    "cloudCover" => 0.89,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 298.7
                ],
                [
                    "time" => 1665039600,
                    "summary" => "Overcast",
                    "icon" => "cloudy",
                    "precipIntensity" => 0.1821,
                    "precipProbability" => 0.14,
                    "precipType" => "rain",
                    "temperature" => 14.83,
                    "apparentTemperature" => 14.83,
                    "dewPoint" => 11.91,
                    "humidity" => 0.83,
                    "pressure" => 1012.9,
                    "windSpeed" => 2.89,
                    "windGust" => 6.68,
                    "windBearing" => 352,
                    "cloudCover" => 0.88,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 298.1
                ],
                [
                    "time" => 1665043200,
                    "summary" => "Overcast",
                    "icon" => "cloudy",
                    "precipIntensity" => 0.0786,
                    "precipProbability" => 0.08,
                    "precipType" => "rain",
                    "temperature" => 17.88,
                    "apparentTemperature" => 17.88,
                    "dewPoint" => 11.65,
                    "humidity" => 0.67,
                    "pressure" => 1012.9,
                    "windSpeed" => 2.7,
                    "windGust" => 6.06,
                    "windBearing" => 349,
                    "cloudCover" => 0.88,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 296.9
                ],
                [
                    "time" => 1665046800,
                    "summary" => "Mostly Cloudy",
                    "icon" => "partly-cloudy-night",
                    "precipIntensity" => 0.0936,
                    "precipProbability" => 0.09,
                    "precipType" => "rain",
                    "temperature" => 16.91,
                    "apparentTemperature" => 16.91,
                    "dewPoint" => 11.37,
                    "humidity" => 0.7,
                    "pressure" => 1013.1,
                    "windSpeed" => 2.49,
                    "windGust" => 5.2,
                    "windBearing" => 343,
                    "cloudCover" => 0.87,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 296.8
                ],
                [
                    "time" => 1665050400,
                    "summary" => "Mostly Cloudy",
                    "icon" => "partly-cloudy-night",
                    "precipIntensity" => 0.1454,
                    "precipProbability" => 0.09,
                    "precipType" => "rain",
                    "temperature" => 15.81,
                    "apparentTemperature" => 15.81,
                    "dewPoint" => 11.08,
                    "humidity" => 0.73,
                    "pressure" => 1013.4,
                    "windSpeed" => 2.35,
                    "windGust" => 4.49,
                    "windBearing" => 335,
                    "cloudCover" => 0.86,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 296.3
                ],
                [
                    "time" => 1665054000,
                    "summary" => "Mostly Cloudy",
                    "icon" => "partly-cloudy-day",
                    "precipIntensity" => 0.1146,
                    "precipProbability" => 0.1,
                    "precipType" => "rain",
                    "temperature" => 14.64,
                    "apparentTemperature" => 14.64,
                    "dewPoint" => 10.94,
                    "humidity" => 0.78,
                    "pressure" => 1013.7,
                    "windSpeed" => 2.24,
                    "windGust" => 3.94,
                    "windBearing" => 324,
                    "cloudCover" => 0.84,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 296.1
                ],
                [
                    "time" => 1665057600,
                    "summary" => "Mostly Cloudy",
                    "icon" => "partly-cloudy-day",
                    "precipIntensity" => 0.0397,
                    "precipProbability" => 0.04,
                    "precipType" => "rain",
                    "temperature" => 14.1,
                    "apparentTemperature" => 14.1,
                    "dewPoint" => 11.29,
                    "humidity" => 0.83,
                    "pressure" => 1014.4,
                    "windSpeed" => 1.98,
                    "windGust" => 3.05,
                    "windBearing" => 321,
                    "cloudCover" => 0.77,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 297.8
                ],
                [
                    "time" => 1665061200,
                    "summary" => "Mostly Cloudy",
                    "icon" => "partly-cloudy-day",
                    "precipIntensity" => 0.0077,
                    "precipProbability" => 0.02,
                    "precipType" => "rain",
                    "temperature" => 14.22,
                    "apparentTemperature" => 14.22,
                    "dewPoint" => 11.87,
                    "humidity" => 0.86,
                    "pressure" => 1014.4,
                    "windSpeed" => 1.83,
                    "windGust" => 2.62,
                    "windBearing" => 325,
                    "cloudCover" => 0.63,
                    "uvIndex" => 1,
                    "visibility" => 16.093,
                    "ozone" => 297.8
                ],
                [
                    "time" => 1665064800,
                    "summary" => "Partly Cloudy",
                    "icon" => "partly-cloudy-day",
                    "precipIntensity" => 0,
                    "precipProbability" => 0,
                    "temperature" => 14.73,
                    "apparentTemperature" => 14.73,
                    "dewPoint" => 12.34,
                    "humidity" => 0.86,
                    "pressure" => 1014.6,
                    "windSpeed" => 1.63,
                    "windGust" => 2.49,
                    "windBearing" => 318,
                    "cloudCover" => 0.55,
                    "uvIndex" => 2,
                    "visibility" => 16.093,
                    "ozone" => 297.6
                ],
                [
                    "time" => 1665068400,
                    "summary" => "Partly Cloudy",
                    "icon" => "partly-cloudy-day",
                    "precipIntensity" => 0,
                    "precipProbability" => 0,
                    "temperature" => 15.34,
                    "apparentTemperature" => 15.34,
                    "dewPoint" => 12.63,
                    "humidity" => 0.84,
                    "pressure" => 1014.8,
                    "windSpeed" => 1.41,
                    "windGust" => 2.31,
                    "windBearing" => 317,
                    "cloudCover" => 0.44,
                    "uvIndex" => 3,
                    "visibility" => 16.093,
                    "ozone" => 297.7
                ],
                [
                    "time" => 1665072000,
                    "summary" => "Partly Cloudy",
                    "icon" => "partly-cloudy-day",
                    "precipIntensity" => 0,
                    "precipProbability" => 0,
                    "temperature" => 16.42,
                    "apparentTemperature" => 16.42,
                    "dewPoint" => 13.07,
                    "humidity" => 0.81,
                    "pressure" => 1014.6,
                    "windSpeed" => 1.22,
                    "windGust" => 2.04,
                    "windBearing" => 339,
                    "cloudCover" => 0.35,
                    "uvIndex" => 4,
                    "visibility" => 16.093,
                    "ozone" => 298.5
                ],
                [
                    "time" => 1665075600,
                    "summary" => "Clear",
                    "icon" => "clear-day",
                    "precipIntensity" => 0,
                    "precipProbability" => 0,
                    "temperature" => 17.55,
                    "apparentTemperature" => 17.55,
                    "dewPoint" => 12.91,
                    "humidity" => 0.74,
                    "pressure" => 1014.1,
                    "windSpeed" => 1.08,
                    "windGust" => 1.66,
                    "windBearing" => 274,
                    "cloudCover" => 0.29,
                    "uvIndex" => 4,
                    "visibility" => 16.093,
                    "ozone" => 297.6
                ],
                [
                    "time" => 1665079200,
                    "summary" => "Clear",
                    "icon" => "clear-day",
                    "precipIntensity" => 0,
                    "precipProbability" => 0,
                    "temperature" => 18.45,
                    "apparentTemperature" => 18.45,
                    "dewPoint" => 12.52,
                    "humidity" => 0.68,
                    "pressure" => 1013.8,
                    "windSpeed" => 1.19,
                    "windGust" => 1.83,
                    "windBearing" => 267,
                    "cloudCover" => 0.23,
                    "uvIndex" => 4,
                    "visibility" => 16.093,
                    "ozone" => 297.1
                ],
                [
                    "time" => 1665082800,
                    "summary" => "Clear",
                    "icon" => "clear-day",
                    "precipIntensity" => 0,
                    "precipProbability" => 0,
                    "temperature" => 19.27,
                    "apparentTemperature" => 19.27,
                    "dewPoint" => 12.45,
                    "humidity" => 0.65,
                    "pressure" => 1013.6,
                    "windSpeed" => 1.24,
                    "windGust" => 1.96,
                    "windBearing" => 272,
                    "cloudCover" => 0.13,
                    "uvIndex" => 3,
                    "visibility" => 16.093,
                    "ozone" => 296.1
                ],
                [
                    "time" => 1665086400,
                    "summary" => "Clear",
                    "icon" => "clear-day",
                    "precipIntensity" => 0,
                    "precipProbability" => 0,
                    "temperature" => 19.7,
                    "apparentTemperature" => 19.7,
                    "dewPoint" => 12.46,
                    "humidity" => 0.63,
                    "pressure" => 1013.4,
                    "windSpeed" => 1.34,
                    "windGust" => 1.98,
                    "windBearing" => 154,
                    "cloudCover" => 0.13,
                    "uvIndex" => 1,
                    "visibility" => 16.093,
                    "ozone" => 294.5
                ],
                [
                    "time" => 1665090000,
                    "summary" => "Clear",
                    "icon" => "clear-day",
                    "precipIntensity" => 0,
                    "precipProbability" => 0,
                    "temperature" => 19.59,
                    "apparentTemperature" => 19.59,
                    "dewPoint" => 12.58,
                    "humidity" => 0.64,
                    "pressure" => 1013.3,
                    "windSpeed" => 1.57,
                    "windGust" => 2.3,
                    "windBearing" => 168,
                    "cloudCover" => 0.12,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 294.5
                ],
                [
                    "time" => 1665093600,
                    "summary" => "Clear",
                    "icon" => "clear-day",
                    "precipIntensity" => 0,
                    "precipProbability" => 0,
                    "temperature" => 18.59,
                    "apparentTemperature" => 18.59,
                    "dewPoint" => 12.37,
                    "humidity" => 0.67,
                    "pressure" => 1013.5,
                    "windSpeed" => 1.83,
                    "windGust" => 2.85,
                    "windBearing" => 174,
                    "cloudCover" => 0.09,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 296.1
                ],
                [
                    "time" => 1665097200,
                    "summary" => "Clear",
                    "icon" => "clear-night",
                    "precipIntensity" => 0,
                    "precipProbability" => 0,
                    "temperature" => 17.73,
                    "apparentTemperature" => 17.73,
                    "dewPoint" => 11.73,
                    "humidity" => 0.68,
                    "pressure" => 1013.8,
                    "windSpeed" => 2.15,
                    "windGust" => 3.61,
                    "windBearing" => 176,
                    "cloudCover" => 0.11,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 297.4
                ],
                [
                    "time" => 1665100800,
                    "summary" => "Clear",
                    "icon" => "clear-night",
                    "precipIntensity" => 0,
                    "precipProbability" => 0,
                    "temperature" => 17.7,
                    "apparentTemperature" => 17.7,
                    "dewPoint" => 11.77,
                    "humidity" => 0.68,
                    "pressure" => 1013.6,
                    "windSpeed" => 2.45,
                    "windGust" => 4.86,
                    "windBearing" => 184,
                    "cloudCover" => 0.17,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 299.1
                ],
                [
                    "time" => 1665104400,
                    "summary" => "Clear",
                    "icon" => "clear-night",
                    "precipIntensity" => 0,
                    "precipProbability" => 0,
                    "temperature" => 17.99,
                    "apparentTemperature" => 17.99,
                    "dewPoint" => 11.97,
                    "humidity" => 0.68,
                    "pressure" => 1013.6,
                    "windSpeed" => 2.56,
                    "windGust" => 4.87,
                    "windBearing" => 195,
                    "cloudCover" => 0.28,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 301.5
                ],
                [
                    "time" => 1665108000,
                    "summary" => "Partly Cloudy",
                    "icon" => "partly-cloudy-night",
                    "precipIntensity" => 0,
                    "precipProbability" => 0,
                    "temperature" => 18.47,
                    "apparentTemperature" => 18.47,
                    "dewPoint" => 12.03,
                    "humidity" => 0.66,
                    "pressure" => 1013.5,
                    "windSpeed" => 2.65,
                    "windGust" => 5.35,
                    "windBearing" => 207,
                    "cloudCover" => 0.42,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 302.6
                ],
                [
                    "time" => 1665111600,
                    "summary" => "Mostly Cloudy",
                    "icon" => "partly-cloudy-night",
                    "precipIntensity" => 0,
                    "precipProbability" => 0,
                    "temperature" => 18.94,
                    "apparentTemperature" => 18.94,
                    "dewPoint" => 11.88,
                    "humidity" => 0.64,
                    "pressure" => 1013.4,
                    "windSpeed" => 2.73,
                    "windGust" => 5.99,
                    "windBearing" => 215,
                    "cloudCover" => 0.6,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 303.1
                ],
                [
                    "time" => 1665115200,
                    "summary" => "Mostly Cloudy",
                    "icon" => "partly-cloudy-night",
                    "precipIntensity" => 0,
                    "precipProbability" => 0,
                    "temperature" => 15.65,
                    "apparentTemperature" => 15.65,
                    "dewPoint" => 11.75,
                    "humidity" => 0.78,
                    "pressure" => 1013.2,
                    "windSpeed" => 2.8,
                    "windGust" => 6.39,
                    "windBearing" => 215,
                    "cloudCover" => 0.7,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 302.5
                ],
                [
                    "time" => 1665118800,
                    "summary" => "Mostly Cloudy",
                    "icon" => "partly-cloudy-night",
                    "precipIntensity" => 0,
                    "precipProbability" => 0,
                    "temperature" => 15.47,
                    "apparentTemperature" => 15.47,
                    "dewPoint" => 11.57,
                    "humidity" => 0.78,
                    "pressure" => 1013,
                    "windSpeed" => 2.87,
                    "windGust" => 6.72,
                    "windBearing" => 215,
                    "cloudCover" => 0.68,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 303
                ],
                [
                    "time" => 1665122400,
                    "summary" => "Mostly Cloudy",
                    "icon" => "partly-cloudy-night",
                    "precipIntensity" => 0,
                    "precipProbability" => 0,
                    "temperature" => 15.17,
                    "apparentTemperature" => 15.17,
                    "dewPoint" => 11.58,
                    "humidity" => 0.79,
                    "pressure" => 1012.9,
                    "windSpeed" => 2.79,
                    "windGust" => 6.1,
                    "windBearing" => 215,
                    "cloudCover" => 0.71,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 304.4
                ],
                [
                    "time" => 1665126000,
                    "summary" => "Mostly Cloudy",
                    "icon" => "partly-cloudy-night",
                    "precipIntensity" => 0,
                    "precipProbability" => 0,
                    "temperature" => 14.66,
                    "apparentTemperature" => 14.66,
                    "dewPoint" => 11.21,
                    "humidity" => 0.8,
                    "pressure" => 1012.6,
                    "windSpeed" => 2.86,
                    "windGust" => 6.46,
                    "windBearing" => 215,
                    "cloudCover" => 0.76,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 307.9
                ],
                [
                    "time" => 1665129600,
                    "summary" => "Mostly Cloudy",
                    "icon" => "partly-cloudy-night",
                    "precipIntensity" => 0,
                    "precipProbability" => 0,
                    "temperature" => 17.56,
                    "apparentTemperature" => 17.56,
                    "dewPoint" => 10.82,
                    "humidity" => 0.65,
                    "pressure" => 1012.3,
                    "windSpeed" => 2.97,
                    "windGust" => 6.72,
                    "windBearing" => 216,
                    "cloudCover" => 0.79,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 310.1
                ],
                [
                    "time" => 1665133200,
                    "summary" => "Mostly Cloudy",
                    "icon" => "partly-cloudy-night",
                    "precipIntensity" => 0,
                    "precipProbability" => 0,
                    "temperature" => 16.62,
                    "apparentTemperature" => 16.62,
                    "dewPoint" => 10.56,
                    "humidity" => 0.67,
                    "pressure" => 1012.1,
                    "windSpeed" => 3,
                    "windGust" => 6.8,
                    "windBearing" => 217,
                    "cloudCover" => 0.81,
                    "uvIndex" => 0,
                    "visibility" => 16.093,
                    "ozone" => 310.7
                ]
            ]
        ],
        "daily" => [
            "summary" => "Rain throughout the week.",
            "icon" => "rain",
            "data" => [
                [
                    "time" => 1664942400,
                    "summary" => "Rain throughout the day.",
                    "icon" => "rain",
                    "sunriseTime" => 1664966820,
                    "sunsetTime" => 1665008400,
                    "moonPhase" => 0.36,
                    "precipIntensity" => 0.5765,
                    "precipIntensityMax" => 1.3823,
                    "precipIntensityMaxTime" => 1665004320,
                    "precipProbability" => 0.99,
                    "precipType" => "rain",
                    "temperatureHigh" => 14.34,
                    "temperatureHighTime" => 1665010800,
                    "temperatureLow" => 13.79,
                    "temperatureLowTime" => 1665010800,
                    "apparentTemperatureHigh" => 14.06,
                    "apparentTemperatureHighTime" => 1665010800,
                    "apparentTemperatureLow" => 14.06,
                    "apparentTemperatureLowTime" => 1665010800,
                    "dewPoint" => 11.6,
                    "humidity" => 0.91,
                    "pressure" => 1014.2,
                    "windSpeed" => 4.61,
                    "windGust" => 11.62,
                    "windGustTime" => 1664974920,
                    "windBearing" => 22,
                    "cloudCover" => 0.97,
                    "uvIndex" => 3,
                    "uvIndexTime" => 1664987340,
                    "visibility" => 15.868,
                    "ozone" => 295.5,
                    "temperatureMin" => 10.38,
                    "temperatureMinTime" => 1664989860,
                    "temperatureMax" => 18.38,
                    "temperatureMaxTime" => 1665024660,
                    "apparentTemperatureMin" => 10.65,
                    "apparentTemperatureMinTime" => 1664989860,
                    "apparentTemperatureMax" => 18.1,
                    "apparentTemperatureMaxTime" => 1665024660
                ],
                [
                    "time" => 1665028800,
                    "summary" => "Partly cloudy throughout the day.",
                    "icon" => "rain",
                    "sunriseTime" => 1665053280,
                    "sunsetTime" => 1665094740,
                    "moonPhase" => 0.4,
                    "precipIntensity" => 0.0667,
                    "precipIntensityMax" => 0.5274,
                    "precipIntensityMaxTime" => 1665028800,
                    "precipProbability" => 0.45,
                    "precipType" => "rain",
                    "temperatureHigh" => 20.01,
                    "temperatureHighTime" => 1665087840,
                    "temperatureLow" => 14.28,
                    "temperatureLowTime" => 1665125280,
                    "apparentTemperatureHigh" => 19.73,
                    "apparentTemperatureHighTime" => 1665087840,
                    "apparentTemperatureLow" => 14.55,
                    "apparentTemperatureLowTime" => 1665125280,
                    "dewPoint" => 12.04,
                    "humidity" => 0.74,
                    "pressure" => 1013.6,
                    "windSpeed" => 2.1,
                    "windGust" => 6.73,
                    "windGustTime" => 1665038460,
                    "windBearing" => 302,
                    "cloudCover" => 0.51,
                    "uvIndex" => 4,
                    "uvIndexTime" => 1665074580,
                    "visibility" => 16.093,
                    "ozone" => 297.9,
                    "temperatureMin" => 13.8,
                    "temperatureMinTime" => 1665058500,
                    "temperatureMax" => 20.01,
                    "temperatureMaxTime" => 1665087840,
                    "apparentTemperatureMin" => 14.07,
                    "apparentTemperatureMinTime" => 1665058500,
                    "apparentTemperatureMax" => 19.73,
                    "apparentTemperatureMaxTime" => 1665087840
                ],
                [
                    "time" => 1665115200,
                    "summary" => "Partly cloudy throughout the day.",
                    "icon" => "partly-cloudy-day",
                    "sunriseTime" => 1665139740,
                    "sunsetTime" => 1665181020,
                    "moonPhase" => 0.43,
                    "precipIntensity" => 0.0106,
                    "precipIntensityMax" => 0.0885,
                    "precipIntensityMaxTime" => 1665176040,
                    "precipProbability" => 0.08,
                    "precipType" => "rain",
                    "temperatureHigh" => 21.07,
                    "temperatureHighTime" => 1665166860,
                    "temperatureLow" => 9.44,
                    "temperatureLowTime" => 1665226800,
                    "apparentTemperatureHigh" => 20.79,
                    "apparentTemperatureHighTime" => 1665166860,
                    "apparentTemperatureLow" => 7.31,
                    "apparentTemperatureLowTime" => 1665226800,
                    "dewPoint" => 11.59,
                    "humidity" => 0.71,
                    "pressure" => 1012.4,
                    "windSpeed" => 3.95,
                    "windGust" => 10.95,
                    "windGustTime" => 1665187440,
                    "windBearing" => 239,
                    "cloudCover" => 0.52,
                    "uvIndex" => 4,
                    "uvIndexTime" => 1665161400,
                    "visibility" => 16.093,
                    "ozone" => 308.4,
                    "temperatureMin" => 11.68,
                    "temperatureMinTime" => 1665201600,
                    "temperatureMax" => 21.07,
                    "temperatureMaxTime" => 1665166860,
                    "apparentTemperatureMin" => 11.95,
                    "apparentTemperatureMinTime" => 1665201600,
                    "apparentTemperatureMax" => 20.79,
                    "apparentTemperatureMaxTime" => 1665166860
                ],
                [
                    "time" => 1665201600,
                    "summary" => "Clear throughout the day.",
                    "icon" => "clear-day",
                    "sunriseTime" => 1665226200,
                    "sunsetTime" => 1665267300,
                    "moonPhase" => 0.47,
                    "precipIntensity" => 0.0294,
                    "precipIntensityMax" => 0.2584,
                    "precipIntensityMaxTime" => 1665219540,
                    "precipProbability" => 0.19,
                    "precipType" => "rain",
                    "temperatureHigh" => 12.88,
                    "temperatureHighTime" => 1665260580,
                    "temperatureLow" => 6.28,
                    "temperatureLowTime" => 1665298380,
                    "apparentTemperatureHigh" => 12.6,
                    "apparentTemperatureHighTime" => 1665260580,
                    "apparentTemperatureLow" => 4.28,
                    "apparentTemperatureLowTime" => 1665298440,
                    "dewPoint" => 1.17,
                    "humidity" => 0.53,
                    "pressure" => 1017.6,
                    "windSpeed" => 4.57,
                    "windGust" => 11.92,
                    "windGustTime" => 1665280380,
                    "windBearing" => 287,
                    "cloudCover" => 0.26,
                    "uvIndex" => 4,
                    "uvIndexTime" => 1665246660,
                    "visibility" => 16.093,
                    "ozone" => 318.2,
                    "temperatureMin" => 8.24,
                    "temperatureMinTime" => 1665230940,
                    "temperatureMax" => 12.88,
                    "temperatureMaxTime" => 1665260580,
                    "apparentTemperatureMin" => 5.77,
                    "apparentTemperatureMinTime" => 1665230820,
                    "apparentTemperatureMax" => 12.6,
                    "apparentTemperatureMaxTime" => 1665260580
                ],
                [
                    "time" => 1665288000,
                    "summary" => "Clear throughout the day.",
                    "icon" => "clear-day",
                    "sunriseTime" => 1665312720,
                    "sunsetTime" => 1665353640,
                    "moonPhase" => 0.51,
                    "precipIntensity" => 0,
                    "precipIntensityMax" => 0,
                    "precipProbability" => 0,
                    "temperatureHigh" => 16.37,
                    "temperatureHighTime" => 1665348240,
                    "temperatureLow" => 9.27,
                    "temperatureLowTime" => 1665388140,
                    "apparentTemperatureHigh" => 16.09,
                    "apparentTemperatureHighTime" => 1665348240,
                    "apparentTemperatureLow" => 8.55,
                    "apparentTemperatureLowTime" => 1665388440,
                    "dewPoint" => 3.36,
                    "humidity" => 0.56,
                    "pressure" => 1021.1,
                    "windSpeed" => 3.29,
                    "windGust" => 10.76,
                    "windGustTime" => 1665288000,
                    "windBearing" => 260,
                    "cloudCover" => 0.13,
                    "uvIndex" => 4,
                    "uvIndexTime" => 1665333000,
                    "visibility" => 16.093,
                    "ozone" => 324.6,
                    "temperatureMin" => 6.28,
                    "temperatureMinTime" => 1665298380,
                    "temperatureMax" => 16.37,
                    "temperatureMaxTime" => 1665348240,
                    "apparentTemperatureMin" => 4.28,
                    "apparentTemperatureMinTime" => 1665298440,
                    "apparentTemperatureMax" => 16.09,
                    "apparentTemperatureMaxTime" => 1665348240
                ],
                [
                    "time" => 1665374400,
                    "summary" => "Partly cloudy throughout the day.",
                    "icon" => "partly-cloudy-day",
                    "sunriseTime" => 1665399180,
                    "sunsetTime" => 1665439920,
                    "moonPhase" => 0.54,
                    "precipIntensity" => 0,
                    "precipIntensityMax" => 0,
                    "precipProbability" => 0,
                    "temperatureHigh" => 17.07,
                    "temperatureHighTime" => 1665425700,
                    "temperatureLow" => 5.56,
                    "temperatureLowTime" => 1665486000,
                    "apparentTemperatureHigh" => 16.79,
                    "apparentTemperatureHighTime" => 1665425700,
                    "apparentTemperatureLow" => 4.4,
                    "apparentTemperatureLowTime" => 1665486000,
                    "dewPoint" => 5.76,
                    "humidity" => 0.59,
                    "pressure" => 1023.8,
                    "windSpeed" => 2.32,
                    "windGust" => 4.41,
                    "windGustTime" => 1665446520,
                    "windBearing" => 247,
                    "cloudCover" => 0.65,
                    "uvIndex" => 3,
                    "uvIndexTime" => 1665419760,
                    "visibility" => 16.093,
                    "ozone" => 326.6,
                    "temperatureMin" => 9.27,
                    "temperatureMinTime" => 1665388140,
                    "temperatureMax" => 17.07,
                    "temperatureMaxTime" => 1665425700,
                    "apparentTemperatureMin" => 8.55,
                    "apparentTemperatureMinTime" => 1665388440,
                    "apparentTemperatureMax" => 16.79,
                    "apparentTemperatureMaxTime" => 1665425700
                ],
                [
                    "time" => 1665460800,
                    "summary" => "Mostly cloudy throughout the day.",
                    "icon" => "partly-cloudy-day",
                    "sunriseTime" => 1665485640,
                    "sunsetTime" => 1665526200,
                    "moonPhase" => 0.57,
                    "precipIntensity" => 0.0059,
                    "precipIntensityMax" => 0.019,
                    "precipIntensityMaxTime" => 1665526320,
                    "precipProbability" => 0.13,
                    "precipType" => "rain",
                    "temperatureHigh" => 28.56,
                    "temperatureHighTime" => 1665521940,
                    "temperatureLow" => 11.26,
                    "temperatureLowTime" => 1665561540,
                    "apparentTemperatureHigh" => 28.28,
                    "apparentTemperatureHighTime" => 1665521940,
                    "apparentTemperatureLow" => 11.53,
                    "apparentTemperatureLowTime" => 1665561540,
                    "dewPoint" => 6.02,
                    "humidity" => 0.59,
                    "pressure" => 1027.5,
                    "windSpeed" => 2.3,
                    "windGust" => 9.91,
                    "windGustTime" => 1665542760,
                    "windBearing" => 229,
                    "cloudCover" => 0.69,
                    "uvIndex" => 3,
                    "uvIndexTime" => 1665506520,
                    "visibility" => 16.093,
                    "ozone" => 280.2,
                    "temperatureMin" => 5.56,
                    "temperatureMinTime" => 1665486060,
                    "temperatureMax" => 28.56,
                    "temperatureMaxTime" => 1665521940,
                    "apparentTemperatureMin" => 4.39,
                    "apparentTemperatureMinTime" => 1665486120,
                    "apparentTemperatureMax" => 28.28,
                    "apparentTemperatureMaxTime" => 1665521940
                ],
                [
                    "time" => 1665547200,
                    "summary" => "Mostly cloudy throughout the day.",
                    "icon" => "rain",
                    "sunriseTime" => 1665572100,
                    "sunsetTime" => 1665612540,
                    "moonPhase" => 0.61,
                    "precipIntensity" => 0.0339,
                    "precipIntensityMax" => 0.2372,
                    "precipIntensityMaxTime" => 1665633600,
                    "precipProbability" => 0.49,
                    "precipType" => "rain",
                    "temperatureHigh" => 26.71,
                    "temperatureHighTime" => 1665572400,
                    "temperatureLow" => 15.83,
                    "temperatureLowTime" => 1665633660,
                    "apparentTemperatureHigh" => 26.43,
                    "apparentTemperatureHighTime" => 1665572400,
                    "apparentTemperatureLow" => 16.1,
                    "apparentTemperatureLowTime" => 1665633660,
                    "dewPoint" => 7.61,
                    "humidity" => 0.51,
                    "pressure" => 1021.3,
                    "windSpeed" => 3.98,
                    "windGust" => 15.03,
                    "windGustTime" => 1665628440,
                    "windBearing" => 193,
                    "cloudCover" => 0.8,
                    "uvIndex" => 7,
                    "uvIndexTime" => 1665594000,
                    "visibility" => 15.979,
                    "ozone" => 181.6,
                    "temperatureMin" => 11.26,
                    "temperatureMinTime" => 1665561540,
                    "temperatureMax" => 28.72,
                    "temperatureMaxTime" => 1665629880,
                    "apparentTemperatureMin" => 11.53,
                    "apparentTemperatureMinTime" => 1665561540,
                    "apparentTemperatureMax" => 28.44,
                    "apparentTemperatureMaxTime" => 1665629880
                ]
            ]
        ],
        "flags" => [
            "sources" => [
                "nwspa",
                "cmc",
                "gfs",
                "hrrr",
                "icon",
                "isd",
                "madis",
                "nam",
                "sref",
                "darksky",
                "nearest-precip"
            ],
            "nearest-station" => 0.743,
            "units" => "si"
        ],
        "offset" => -4
    ],
    "weather_all_past" => [
        "2022-10-09" => [
            "currently" => "Clear",
            "hourly" => "Clear throughout the day.",
            "daily" => "Clear throughout the day."
        ],
        "2022-10-08" => [
            "currently" => "Partly Cloudy",
            "hourly" => "Partly Cloudy",
            "daily" => "Light rain throughout the day."
        ],
    ],
];
